#程序日志位置
log: std
#日志等级
log_level: "debug"
#微信监听端口
listen_port: 8000
#微信api地址
wechat_api_address: "127.0.0.1:8000"
#消息监听转发地址
message_notify_url: []
qun_manager:
  enable_word: ["启用群管理"]
  disbale_word: ["退出群管理"]
module:
  chatgpt:
    ai_session: ""
